name: 'Tester #17'
favicon: null
layout_spectrum: 0.08406
typography_spectrum: 0.09248425927944481
title: 'Tester #17'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5eaeb9'
    - '#ffffff'
    - '#3a777e'
    - '#0f3b40'
    - '#98d0d6'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
