name: 'Tester #17'
favicon: null
layout_spectrum: 0.47371756029315293
typography_spectrum: 0.09248425927944481
title: 'Tester #17'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.08345350227318704
  lightness: 0.9134427022654563
  saturation: 0.2555531079415232
  rhythmicContrast: 0.7177470091264695
purpose: []
